init:
- appveyor version
- git --version
- ps: Write-Host $env:APPVEYOR_BUILD_WORKER_IMAGE
- ps: Write-Host $env:APPVEYOR_BUILD_WORKER_CLOUD

install:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

assembly_info:
  patch: true

build_script:
- msbuild MySimpleApp.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: '**\*.msi'
    name: MyApp
